### PR TITLE
Progress indicator markup-kit

### PR DESCRIPTION
**Pull request by jackiejakob**
Any feedback welcome!

### CODE REVIEW

**Comment by jackiejakob** [comment]
@davodey @dengeist @pauljadam  Updated per changes requested. One thing EJ and I debating was if we should add role=alert to the loading progress indicator since that percent changes over time. Thoughts?

**Comment by pauljadam** [comment]
@jackiejakob  I think that's a good idea even though it's not mentioned to do it in the ARIA spec for progressbar. I found this demo that worked good! https://labs.levelaccess.com/index.php/Progress_Bar_with_ARIA_Live_Regions they use aria-live=polite which I think makes sense because we may not want to interrupt the user with all the announcements. But you could still use role=alert. I think it's fine to speak the progress as long as it does not get too noisy and speak every single percentage.

**Comment by jackiejakob** [comment]
@pauljadam  Hm, the framework video shows it counting up each percent, so would that get annoying like you said (depending on how fast loading is)? https://uxframework.pearson.com/c/progress-bar/v2.0.1#progress-indicators--animated-progress-bar

**Comment by pauljadam** [comment]
@jackiejakob yeah I'm not exactly sure how it would sound, if it would sound ok or bad, I think might need to just build it and put some aria-live attributes on there to test how it sounds, e.g. try role=alert and then try role=status to do assertive and polite regions and see if they sound OK, but it might be too much noise to hear every single percentage spoken. If it's moving very slow then it might not be too annoying but might be more annoying if speaking really fast every single digit.

**Comment by davodey** [comment]
@dengeist and I talked about this, and we think it should be a polite region.  We definitely don't want each percentage spoken, that could get crazy.

**Comment by jackiejakob** [comment]
@davodey @pauljadam @dengeist  Updates to status messaging have been made. There's a script in the loading.html that'll count up sequentially to test the amount of messaging that is read.
Let me know if you see any additional changes. Thanks!

**Pull request merged**
