### PR TITLE
Feature/file uploader/minimize

### PR DESCRIPTION
**Pull request by davodey**
Added a minimize feature to the file upload component modal.

### CODE REVIEW

**Comment by davodey** [comment]
@dengeist I think we can remove the markup-kit and all the stuff not pertaining to the launch of the modal.  We can slim it down for sure.  - is that what you're referring to?

**Comment by dengeist** [comment]
@davodey yeah! You would know better than I would what we can trim. I think it makes sense to do that now before we move on to the web component version, so go ahead and do that and I'll approve :)

**Comment by davodey** [comment]
@dengeist files removed.  I also attempted to fix the FOUC by merging in the newer modal style.

**Comment by davodey** [comment]
@dengeist perfect.

**Pull request merged**
