### PR TITLE
Component/footer

### PR DESCRIPTION
**Pull request by sarahvc**
Converted footer html/css into web component.

### CODE REVIEW

**Comment by sarahvc** [comment]
@dengeist Hi EJ, Thanks for the review! I'm made changes accordingly, let me know if it's good now. Thanks!

**Comment by davodey** [comment]
@sarahvc the only issue I see is in IE11.  Screenshot attached.

screen shot 2018-11-14 at 9 02 57 pm

**Comment by sarahvc** [comment]
@davodey I added a little fix to the css now the link color be correct in IE11. But for the position issue, I noticed that if I change the resolution, the ul and the p will be where they should be...The issue only shows up when you first open this in browser stack. I wonder what should I do with this...Any idea?

**Comment by davodey** [comment]
@sarahvc I'm actually ok with the positioning in IE11.  @antelopeb what do you think?

**Comment by antelopeb** [comment]
I'm good with it. @dengeist -- are we good to go on this one?

**Comment by dengeist** [comment]
All good! Thanks for this, @sarahvc! :)

**Pull request merged**
