### PR TITLE
Markup/datepicker

### PR DESCRIPTION
**Pull request by davodey**
My first pass at the datepicker is complete.  Im sure I missed a few things :)

### CODE REVIEW

**Comment by pauljadam** [comment]
@davodey I see the date picker does not have a button to open the calendar view, one issue is that the screen reader user would not know that they can hit the down arrow key to open the calendar. I'm thinking it would be better to have that explicit button to show the calendar date picker, also so that dragon speech users have a control to activate to display it.

I'm not sure if the user should click into the text input box to show the calendar because they can't manually type a date. I think users would want the option to either manually type the date or to use the calendar widget. 

Once inside the calendar view the page up and page down keys and the home and end keys are not working. I think the standard is that page up and page down move between months and home and end get takes you to the first date or the last date in the month.  This demo also uses alt + page down to move between years https://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm 

The currently selected date is not conveyed to the screen reader user. It's not speaking a pressed state. 

image

Looks like next and previous month buttons are not working. Once I hit enter on the next or previous month button the calendar closes and there's no way to get keyboard focus back into it.

**Comment by davodey** [comment]
@pauljadam thank you!  I have a few of your requests done, and will finish up tomorrow.

**Comment by jackiejakob** [comment]
Should calendar close on Escape? You can't close it (or tab out of it) via keyboard. You can click out of it to close it. 

Do you think we need date entry validation to match the timepicker?

Calendar renders well in IE here. Thanks!

**Comment by pauljadam** [comment]
Yes I think it should close on escape key please. Thanks!

**Pull request merged**
