### PR TITLE
Carousel

### PR DESCRIPTION
**Pull request by hebernard**
Does anyone have any feedback on this component? I just converted it to a web component and added a few small accessibility things but i don't know if I'm missing anything.

### CODE REVIEW

**Comment by davodey** [comment]
@hebernard overall this looks really good, but I think we should change the way we add slides.  

Instead of using data, lets use the <slot> attribute and allow the user to put in whatever content they want.  That way, they can style whats in the carousel, but not the carousel itself and add any markup of their choosing.

**Review by davodey — CHANGES_REQUESTED** [review]
See general comments.

**Comment by pauljadam** [comment]
@hebernard Carousel needs a pause button to stop the movement. 

The next and previous slide buttons need an aria-label for the accessible name.
image

I would remove the aria-live attribute as well because it's set to "off" which is the default so the attribute is not needed. I don't really recommend that carousels use ARIA live regions.

**Comment by hebernard** [comment]
Thank you all!

**Review by davodey — APPROVED** [review]
Looks good.

**Pull request merged**
