### PR TITLE
Drawer markup

### LINKED ISSUE #180: Drawer should close with the Escape key

### LINKED ISSUE #181: Drawer should animate on open/close

### PR DESCRIPTION
**Pull request by dengeist**
The complete drawer markup-kit.

Resolves #180 - Drawer closes with escape key
Resolves #181 - Drawer transitions animate

Todos:
- [x] Get accessibility feedback from @pauljadam. Paul, aside from any general accessibility opinions, I'd specifically like to know what you think of the following:
  - The topic titles in the drawers being buttons (and those buttons being `aria-labelledby` the following paragraphs)
  - Making the headings the first focusable item in each panel.

### CODE REVIEW

**Comment by pauljadam** [comment]
@dengeist The drawer widgets don't seem to be working for me in in Safari and Chrome. 

I think setting focus to the heading of the drawer when it opens is a good idea yes. I do this for skip links. 

Not sure about the other question, is that example inside the code for me to look at? 

Also I'd say you can avoid using aria-hidden=true/false here and just use CSS display:none then it's less code to worry about, I see folks mess up aria-hidden so much I always recommend avoiding it unless you really need it.

**Comment by dengeist** [comment]
Resolved, @pauljadam! Silly typo on my part. :)

**Comment by pauljadam** [comment]
@dengeist thanks it's working now. 

I think the X buttons could be more meaningful and specific e.g. they could say "Close Help Topics" rather than just "close drawer" 
image

If you wanted to, you could also code these as non-modal role=dialog elements and then set focus to the X button and the dialog title would be spoken automatically without setting focus to the dialog heading. Either way can work though, you don't need to make it a dialog.

**Comment by pauljadam** [comment]
@dengeist  I think it still makes sense to make it say "Close Help Topics" once in the details sub level views. 

One other issue I'm seeing is that when I Shift + Tab backwards in the tab ring I never get to the X button, I only get to the X button when tabbing forward in the tab ring but not backwards.

**Comment by dengeist** [comment]
Changed the aria-label and fixed the tab-trap, @pauljadam :)

**Comment by pauljadam** [comment]
@dengeist there's a bug with aria-hidden=true not being removed from the drawer sometimes when I open and close it a few times.

You should not really need to use aria-hidden to hide the drawer when it's not visible, all you need is CSS for that.  

image

**Comment by dengeist** [comment]
Thanks for catching that @pauljadam . Also fixed.

**Comment by pauljadam** [comment]
@dengeist  Thanks! It's fixed.

**Comment by antelopeb** [comment]
@dengeist -- looks good. One change needed. The overflow on the drawer when the content is too long doesn't scroll, it just overflows and get's cut off.

**Comment by davodey** [comment]
@dengeist Code looks great.

Can we speed up the animation a bit?  I also noticed that in the detail drawer when you click a sub item, the title expands a bit.  Can we keep these the same height so it doesn't appear janky?

**Comment by dengeist** [comment]
@davodey @antelopeb Tried to address your issues! Dave, let me know if you want the animation to be faster. I took it from 1 second to 0.6 seconds.

**Comment by davodey** [comment]
@antelopeb the scroll issue has been fixed. going to dismiss review so we can merge.

**Pull request merged**
