### PR TITLE
Component/coachmark

### PR DESCRIPTION
**Pull request by davodey**

### CODE REVIEW

**Comment by pauljadam** [comment]
@davodey right now the buttons don't really indicate that they open a pop up dialog to the screen reader user. I think maybe we should use aria-haspopup="dialog" so they hear more than just the button role spoken http://w3c.github.io/aria/#aria-haspopup

image
I'm not sure it's required but I usually ask folks to make the X buttons specifically say the name of the thing they close e.g. it could say "Close This is informational dialog". It's probably more of a problem if there are multiple x buttons visible on the screen at the same time. 

image
Related to that is the Got it button which is not really meaningful to a blind user, could it say something more specific also like "Got it, Close This is informational dialog". 

Thanks!

**Comment by davodey** [comment]
@pauljadam hows this?

**Comment by pauljadam** [comment]
@davodey thanks! that fixes the issues inside the dialogs.

I'm still thinking we should have aria-haspopup=dialog on the buttons that open the dialog though. 

Thanks!

image

**Comment by davodey** [comment]
@pauljadam Should be all set.

**Comment by pauljadam** [comment]
@davodey Thanks!

The only small issue I can find is there is no space separating the name of the dialog from the string dialog in the aria-label values, e.g. 
aria-label="close This is specialdialog"
screen readers may pronounce it incorrectly since there's no space between specialdialog

**Comment by davodey** [comment]
@pauljadam fixed

**Pull request merged**
