### PR TITLE
Loading Indicator component

### PR DESCRIPTION
**Pull request by dengeist**
Fully implemented and ready for feedback!

Questions:
- Do we want to give consumers any control over `aria-label` or `aria-valuetext`? Right now, `aria-label` starts out as "Loading" and becomes "Loaded", and `aria-valuetext` is always "Loading indicator"
- Is `pearson-loading-indicator` too long a name?

### CODE REVIEW

**Comment by jackiejakob** [comment]
I didn't see any issues with the component, but not sure about answers to your two questions...

**Comment by davodey** [comment]
@dengeist I don't think we should give consumers control over the aria text. Let's call it something like 'pearson-loader'

**Comment by dengeist** [comment]
@davodey I saw over in #209 that you are using a separate template to create a live region. I didn't even think of that for this loading indicator; very nice. Should I try something like that, so that we don't have to trust the consumer to make a live region?

**Comment by davodey** [comment]
@dengeist totally!

**Comment by jackiejakob** [comment]
@dengeist Forgot to test IE/Edge

Win8.1 and Win10/IE11 - button does not launch loading indicator; could not test component
Win10/Edge16-18 - Works okay. The font loads a tiny bit smaller and the jumps bigger in the first milliseconds that the loading indicator appears but not a breaking issue (and can't replicate after it loads for the first time in each browser).

**Comment by dengeist** [comment]
@jackiejakob fixed the component not appearing on IE11. The font issue you see is probably due to the font not being 100% loaded on first visit

**Pull request merged**
