### PR TITLE
progress indicator complete

### PR DESCRIPTION
**Pull request by davodey**

### CODE REVIEW

**Comment by jackiejakob** [comment]
@davodey Looks good!  

I'm getting a console error around the liveregion.
screen shot 2019-01-11 at 6 40 39 am
Also curious if we should allow for the alert message ("Done loading") to be customizable by the user. Not sure if we should allow for more specificity to declare what is done loading. @pauljadam , what do you think?

Not sure this is an issue, but want to bring it up just in case: The alert message pops up before the bar changes to 100% -- so after I close the message, the bar goes to 100 before starting over at 0.
screen shot 2019-01-11 at 6 41 45 am

Lastly, something I'm curious about: For the attributes, are we assuming users will know, or figure out, what they can select or will that be in documentation? E.g., For the "alignment" attribute, I tried "right" but the actual value is "right-aligned" (I know, I wrote the css and should have known).

**Comment by pauljadam** [comment]
Yes the alerts are being spoken too often I think and there's no pause button to stop the progress bar demo so it's an infinite loop of live region messages and JavaScript alert pop ups. 

I think if the demo either stopped automatically after running once and then had a replay button that would not seem as noisy or it could have a pause/resume buttons to stop the noise. 

Do we need the JavaScript alert message? I've not seen those in custom progress indicators.

**Comment by dengeist** [comment]
I'll definitely add the ability to stop/pause for the purposes of the demo, and get rid of the alert as well, but we already know that the real-world use will be a bar that only runs once and cannot be paused. If you have any thoughts on this throttling approach, that would be super helpful!

**Comment by pauljadam** [comment]
@dengeist  I'm not sure you have to use a throttling approach if the real world example simply loads once and then shuts up. But it could be great also, would just have to try it out to see :) I'm good with either approach.

**Comment by dengeist** [comment]
I think I explained this poorly. By throttling, i mean the frequency of changes to the live region. For instance, if the text changes 99 times for the growth from 1% to 100% of progress, we want to throttle how often a live-region actually publishes a change.

**Comment by pauljadam** [comment]
@dengeist so maybe only speak every 10 percent to the live region? I think that would be a good idea for less noise.

**Comment by davodey** [comment]
@dengeist @pauljadam for some reason, VO was speaking the label everytime it was updated, even without an aria-live attribute.  I added an aria-hidden to the label update and now the aria-live region works correctly.

**Comment by davodey** [comment]
Thanks @jackiejakob well add the correct attributes to the documentation.  I don't think we should have dev's update the aria region with their own text.  Let's hold off on that for now.

**Comment by pauljadam** [comment]
image
Should the 2nd progress indicator example be aria-labelledby the text that is above it? E.g. right now it just says 50% progress indicator but I don't know what type of progress this is related to. OR does it need that text above the indicator set as the aria-valuetext? I have a demo http://pauljadam.com/demos/progressbar.html

**Pull request merged**
