### PR TITLE
Component/file uploader

### PR DESCRIPTION
**Pull request by davodey**
- Refactored code to use event listeners, and is more maintainable
- Uses ajax to post and delete files
- Ability to add multiple uploads to an application

### CODE REVIEW

**Comment by dengeist** [comment]
@davodey Seeing an interesting VO/Safari bug on MacOS: Safari will not announce the name of the Browse Files button, even when you tab away and back.

screen shot 2018-11-07 at 2 49 27 pm

This is what the user hears when the dialog opens. Notice no mention of the Browse Files button. Is it aria-hidden somehow?

Chrome announces the button just fine.

**Comment by davodey** [comment]
@dengeist It has something to do with the upload component being inside the modal.  I uploaded a file and none of the other buttons inside work with VO on safari either.  

Would you mind taking a look for me?

**Comment by sarahvc** [comment]
@davodey @dengeist I added type="button" to the browse files button, now I can hear the VO on safari saying "ur on a button blahblah". Let me know if this fix the issue. Thanks!

**Comment by davodey** [comment]
@sarahvc NICE!  @dengeist will this work?

**Pull request merged**
