### PR TITLE
Component/modal

### PR DESCRIPTION
**Pull request by davodey**
The new modal is now complete.  Completely re-written, It uses the same api with an additional option of 'showonload'.  Adding this attribute will launch the modal when the page loads.

@vangeri and @hebernard I'm including you so you can get a feel for the WC review process.  I'ts pretty informal, but important none the less.  Feel free to make comments, suggestions, questions.

### CODE REVIEW

**Comment by jackiejakob** [comment]
@davodey Does focus need to go somewhere when the modal closes, or are we leaving that up to the project/end user to control themselves?

**Comment by davodey** [comment]
@jackiejakob it goes back to the button that triggered it.  Since all the styling is removed from button, no focus rings show.  If you click enter though, it should work.

**Comment by jackiejakob** [comment]
@davodey Ah, okay. That does not happen if I have "showonload" attr on the modal, but works when that isn't there.

**Comment by davodey** [comment]
@jackiejakob correct, because show on load doesn't have a trigger that opened it.

**Comment by jackiejakob** [comment]
@davodey OK. And should that extra Close button do anything?

**Comment by davodey** [comment]
@jackiejakob no, that is a demo button inside the modal being called from index.html, not the component itself.

**Comment by jackiejakob** [comment]
@davodey OK cool, just checking in case you hooked up an event to be called by it. If you hide the cancel button (hidecancel), it prevents the tabbing from cycling through. That is, I'm stopped at the success button and tabbing doesn't go anywhere.

**Comment by davodey** [comment]
@jackiejakob good catch, there was a duplicate parameter name preventing the functions from running.  This is fixed and pushed.

**Pull request merged**
