### PR TITLE
Dropdown HTML, CSS, JS

### PR DESCRIPTION
**Pull request by davodey**
dropdown markup complete.

### CODE REVIEW

**Comment by jackiejakob** [comment]
@davodey @dengeist Do you think there will be a need for single select (menuitemradio) for dropdown?

**Comment by davodey** [comment]
@jackiejakob so we have a single select in here, but it doesnt use radio buttons.

**Comment by dengeist** [comment]
Thanks for pointing that out, @jackiejakob. I'm gonna make sure our single-select menus use `menuitemradio` since that's more semantically correct

**Comment by davodey** [comment]
@dengeist should we change the markup so they are radios?

**Comment by dengeist** [comment]
@davodey nah, the markup we have is mostly fine; the `menuitemradio` and `menuitemcheckbox` is for communicating if menu items are single- or multiselect.

Made some changes for you to review as well.

**Comment by davodey** [comment]
@dengeist thank you sir!  looks really good.

**Pull request merged**
